# config/packages/security.yaml
security:
    # Configure les hashers de mot de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Définition des fournisseurs d'utilisateurs
    providers:
        database_users:
            entity:
                class: App\Entity\User
                property: email

    # Configuration des firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: database_users
            custom_authenticator: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: account  # Redirige vers la route 'account' après la déconnexion

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

    # Règles de contrôle d'accès
    access_control:
        - { path: ^/compte, roles: ROLE_USER }
        - { path: ^/commande, roles: ROLE_USER }
